version: '3.8'

services:
  socket-server:
    image: socket-server
    container_name: ss-cont
    build:
      context:
        ./server
      dockerfile:
        Dockerfile

  socket-client:
    image: socket-client
    container_name: sc-cont
    build:
      context:
        ./client
      dockerfile:
        Dockerfile
